import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="p-4 border-b">
            <div className="max-w-6xl mx-auto flex items-center justify-between">
              <div className="flex items-center space-x-6">
                <Link href="/" className="text-xl font-bold text-foreground hover:text-foreground/80 transition-colors">
                  SaaS App
                </Link>
                <nav className="hidden md:flex space-x-4">
                  <SignedIn>
                    <Link href="/dashboard" className="text-foreground/70 hover:text-foreground transition-colors">
                      Dashboard
                    </Link>
                    <Link href="/ai" className="text-foreground/70 hover:text-foreground transition-colors">
                      AI Assistant
                    </Link>
                  </SignedIn>
                  <Link href="/pricing" className="text-foreground/70 hover:text-foreground transition-colors">
                    Pricing
                  </Link>
                  <Link href="/premium" className="text-foreground/70 hover:text-foreground transition-colors">
                    Premium Content
                  </Link>
                </nav>
              </div>

              <div className="flex items-center space-x-4">
                <SignedOut>
                  <div className="flex gap-4">
                    <SignInButton />
                    <SignUpButton />
                  </div>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
